# Generated by Django 3.2.8 on 2023-03-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('value', models.FloatField(default=0, max_length=50)),
                ('classname', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'ClassMetricData',
            },
        ),
        migrations.CreateModel(
            name='ProjectMetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('value', models.FloatField(default=0, max_length=50)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.version', verbose_name='所属版本')),
            ],
            options={
                'db_table': 'ProjectMetricData',
            },
        ),
        migrations.CreateModel(
            name='ModuleMetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('value', models.FloatField(default=0, max_length=50)),
                ('module', models.CharField(max_length=50, null=True)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.version', verbose_name='所属版本')),
            ],
            options={
                'db_table': 'ModuleMetricData',
            },
        ),
        migrations.CreateModel(
            name='MethodMetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('value', models.FloatField(default=0, max_length=50)),
                ('method', models.CharField(max_length=100, null=True)),
                ('classname', models.ManyToManyField(to='evaluator.ClassMetricData')),
            ],
            options={
                'db_table': 'MethodMetricData',
            },
        ),
        migrations.AddField(
            model_name='classmetricdata',
            name='module',
            field=models.ManyToManyField(to='evaluator.ModuleMetricData'),
        ),
    ]
