# Generated by Django 3.2.8 on 2023-03-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, null=True, verbose_name='文件名称')),
                ('color', models.CharField(default='#FFFFFF', max_length=30, null=True, verbose_name='圆圈颜色')),
                ('relation', models.TextField(blank=True, default='', null=True, verbose_name='依赖变化')),
                ('end', models.BooleanField(blank=True, default=False, null=True)),
                ('value', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('qualifiedName', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='文件完整名称')),
                ('catelogue_type', models.SmallIntegerField(default=1, verbose_name='目录级别')),
                ('parent_catelogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cluster.treemapdata', verbose_name='父类目录')),
                ('version_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.version', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'TreeMapData',
                'verbose_name_plural': 'TreeMapData',
                'db_table': 'TreeMapData',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClusterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, null=True, verbose_name='文件名称')),
                ('color', models.CharField(default='#FFFFFF', max_length=30, null=True, verbose_name='圆圈颜色')),
                ('relation', models.TextField(blank=True, default='', null=True, verbose_name='依赖变化')),
                ('changeLoc', models.IntegerField(default=0, null=True, verbose_name='修改频率')),
                ('value', models.FloatField(default=0.0, null=True, verbose_name='半径')),
                ('cluster', models.SmallIntegerField(default=0, verbose_name='目录级别')),
                ('cluster_algo', models.CharField(default='', max_length=30)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cluster.clusterdata', verbose_name='父类结点')),
                ('version_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.version', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'ClusterData',
                'verbose_name_plural': 'ClusterData',
                'db_table': 'ClusterData',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CatelogueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, null=True, verbose_name='文件名称')),
                ('color', models.CharField(default='#FFFFFF', max_length=30, null=True, verbose_name='圆圈颜色')),
                ('relation', models.TextField(blank=True, default='', null=True, verbose_name='依赖变化')),
                ('changeLoc', models.IntegerField(default=0, null=True, verbose_name='修改频率')),
                ('value', models.FloatField(default=0.0, null=True, verbose_name='半径')),
                ('catelogue_type', models.SmallIntegerField(choices=[(1, '一级目录'), (2, '二级目录')], default=1, verbose_name='目录级别')),
                ('parent_catelogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cluster.cateloguedata', verbose_name='父类目录')),
                ('version_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.version', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'CatelogueData',
                'verbose_name_plural': 'CatelogueData',
                'db_table': 'CatelogueData',
                'ordering': ['id'],
            },
        ),
    ]
