# Generated by Django 3.2.8 on 2023-03-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, null=True, verbose_name='衰退模块')),
                ('problem_metric', models.CharField(max_length=50, null=True, verbose_name='问题指标')),
                ('problem_degree', models.CharField(max_length=50, null=True, verbose_name='衰退程度')),
                ('end', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_version', to='project.version', verbose_name='衰退结束版本')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='所属项目')),
                ('start', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_version', to='project.version', verbose_name='衰退开始版本')),
            ],
            options={
                'db_table': 'DecayData',
            },
        ),
    ]
